version: "3.1"

services:
  rasa:
    image: rasa/rasa:3.6.10
    ports:
      - "5005:5005"
    volumes:
      - ./:/app
    command: >
      run
      --enable-api
      --cors "*"
      --debug

  action_server:
    image: rasa/rasa-sdk:3.6.1
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
